(function(){var h={},mt={},c={id:"0c5868624a7d3200457f08c5d92de758",dm:["qiuliuliang.com"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,apps:''};var p=!0,q=null,t=!1;mt.h={};mt.h.xa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.la=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,f,g){var d;g.B&&(d=new Date,d.setTime(d.getTime()+g.B));document.cookie=a+"="+f+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(d?"; expires="+d.toGMTString():"")+(g.Ba?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:q};mt.event={};mt.event.d=function(a,f,g){a.attachEvent?a.attachEvent("on"+f,function(d){g.call(a,d)}):a.addEventListener&&a.addEventListener(f,g,t)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=t};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=g[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function f(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===q)return"null";if(d instanceof Array){var g=["["],n=d.length,k,e,b;for(e=0;e<n;e++)switch(b=d[e],typeof b){case "undefined":case "function":case "unknown":break;default:k&&g.push(","),g.push(mt.m.stringify(b)),k=1}g.push("]");return g.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+f(d.getMonth()+1)+"-"+f(d.getDate())+"T"+f(d.getHours())+":"+f(d.getMinutes())+":"+f(d.getSeconds())+'"';k=["{"];e=mt.m.stringify;for(n in d)if(Object.prototype.hasOwnProperty.call(d,n))switch(b=
d[n],typeof b){case "undefined":case "unknown":case "function":break;default:g&&k.push(","),g=1,k.push(e(n)+":"+e(b))}k.push("}");return k.join("")}}}();mt.lang={};mt.lang.e=function(a,f){return"[object "+f+"]"==={}.toString.call(a)};mt.lang.ya=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Aa=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.w=function(){if(!mt.localStorage.f)try{mt.localStorage.f=document.createElement("input"),mt.localStorage.f.type="hidden",mt.localStorage.f.style.display="none",mt.localStorage.f.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.f)}catch(a){return t}return p};
mt.localStorage.set=function(a,f,g){var d=new Date;d.setTime(d.getTime()+g||31536E6);try{window.localStorage?(f=d.getTime()+"|"+f,window.localStorage.setItem(a,f)):mt.localStorage.w()&&(mt.localStorage.f.expires=d.toUTCString(),mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.setAttribute(a,f),mt.localStorage.f.save(document.location.hostname))}catch(l){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var f=a.indexOf("|"),g=a.substring(0,f)-0;if(g&&g>(new Date).getTime())return a.substring(f+1)}}else if(mt.localStorage.w())try{return mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.getAttribute(a)}catch(d){}return q};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.w())try{mt.localStorage.f.load(document.location.hostname),mt.localStorage.f.removeAttribute(a),mt.localStorage.f.save(document.location.hostname)}catch(f){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,f){if(window.sessionStorage)try{window.sessionStorage.setItem(a,f)}catch(g){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):q};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.I={};mt.I.log=function(a,f){var g=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=q;g=window[d]=q;f&&f(a)};g.src=a};mt.t={};
mt.t.ca=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var f=navigator.plugins["Shockwave Flash"];f&&f.description&&(a=f.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(f=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=f.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.t.V=function(a,f,g,d,l){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+d+'"><param name="movie" value="'+f+'" /><param name="flashvars" value="'+(l||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+d+'" src="'+f+'" flashvars="'+(l||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(a,f){var g=a.match(RegExp("(^|&|\\?|#)("+f+")=([^&#]*)(&|$|#)",""));return g?g[3]:q};mt.url.wa=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:q};mt.url.$=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):q};mt.url.K=function(a){return(a=mt.url.$(a))?a.replace(/:\d+$/,""):a};mt.url.va=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):q};
h.z={ia:"http://tongji.baidu.com/hm-web/welcome/ico",P:"hm.baidu.com/hm.gif",S:"baidu.com",fa:"hmmd",ga:"hmpl",ea:"hmkw",da:"hmci",ha:"hmsr",l:0,g:Math.round(+new Date/1E3),protocol:"https:"==document.location.protocol?"https:":"http:",za:0,sa:6E5,ta:10,ua:1024,ra:1,r:2147483647,Q:"cc cf ci ck cl cm cp cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={i:{},d:function(a,g){this.i[a]=this.i[a]||[];this.i[a].push(g)},o:function(a,g){this.i[a]=this.i[a]||[];for(var d=this.i[a].length,l=0;l<d;l++)this.i[a][l](g)}};return h.p=a})();
(function(){function a(a,d){var l=document.createElement("script");l.charset="utf-8";f.e(d,"Function")&&(l.readyState?l.onreadystatechange=function(){if("loaded"===l.readyState||"complete"===l.readyState)l.onreadystatechange=q,d()}:l.onload=function(){d()});l.src=a;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(l,n)}var f=mt.lang;return h.load=a})();
(function(){var a=h.z,f=mt.t,g={init:function(){if(""!==c.icon){var d;d=c.icon.split("|");var g=a.ia+"?s="+c.id,n=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+d[0]+"."+d[1];switch(d[1]){case "swf":d=f.V("HolmesIcon"+a.g,n,d[2],d[3],"s="+g);break;case "gif":d='<a href="'+g+'" target="_blank"><img border="0" src="'+n+'" width="'+d[2]+'" height="'+d[3]+'"></a>';break;default:d='<a href="'+g+'" target="_blank">'+d[0]+"</a>"}document.write(d)}}};h.p.d("pv-b",g.init);return g})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.A.aa()+","+h.A.Z();h.b.j()}}function f(){clearTimeout(x);var a;v&&(a="visible"==document[v]);y&&(a=!document[y]);e="undefined"==typeof a?p:a;if((!k||!b)&&e&&m)w=p,s=+new Date;else if(k&&b&&(!e||!m))w=t,r+=+new Date-s;k=e;b=m;x=setTimeout(f,100)}function g(b){var a=document,d="";if(b in a)d=b;else for(var e=["webkit","ms","moz","o"],s=0;s<e.length;s++){var r=e[s]+b.charAt(0).toUpperCase()+b.slice(1);if(r in a){d=
r;break}}return d}function d(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))m="focus"==b.type||"focusin"==b.type?p:t,f()}var l=mt.event,n=h.p,k=p,e=p,b=p,m=p,u=+new Date,s=u,r=0,w=p,v=g("visibilityState"),y=g("hidden"),x;f();(function(){var b=v.replace(/[vV]isibilityState/,"visibilitychange");l.d(document,b,f);l.d(window,"pageshow",f);l.d(window,"pagehide",f);"object"==typeof document.onfocusin?(l.d(document,"focusin",d),l.d(document,"focusout",d)):(l.d(window,"focus",d),
l.d(window,"blur",d))})();h.A={aa:function(){return+new Date-u},Z:function(){return w?+new Date-s+r:r}};n.d("pv-b",function(){l.d(window,"unload",a())});return h.A})();
(function(){function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var f=b[e];d.e(f,"Object")||d.e(f,"Array")?a(f):b[e]=String(f)}}function f(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b}var g=mt.I,d=mt.lang,l=mt.m,n=h.z,k=h.p,e={L:q,n:[],s:0,M:t,init:function(){e.c=0;e.L={push:function(){e.G.apply(e,arguments)}};k.d("pv-b",function(){e.W();e.X()});k.d("pv-d",e.Y);k.d("stag-b",function(){h.b.a.api=e.c||e.s?e.c+"_"+e.s:""});k.d("stag-d",function(){h.b.a.api=
0;e.c=0;e.s=0})},W:function(){var b=window._hmt;if(b&&b.length)for(var a=0;a<b.length;a++){var d=b[a];switch(d[0]){case "_setAccount":1<d.length&&/^[0-9a-z]{32}$/.test(d[1])&&(e.c|=1,window._bdhm_account=d[1]);break;case "_setAutoPageview":if(1<d.length&&(d=d[1],t===d||p===d))e.c|=2,window._bdhm_autoPageview=d}}},X:function(){if("undefined"===typeof window._bdhm_account||window._bdhm_account===c.id){window._bdhm_account=c.id;var b=window._hmt;if(b&&b.length)for(var a=0,f=b.length;a<f;a++)d.e(b[a],
"Array")&&"_trackEvent"!==b[a][0]&&"_trackRTEvent"!==b[a][0]?e.G(b[a]):e.n.push(b[a]);window._hmt=e.L}},Y:function(){if(0<e.n.length)for(var b=0,a=e.n.length;b<a;b++)e.G(e.n[b]);e.n=q},G:function(b){if(d.e(b,"Array")){var a=b[0];if(e.hasOwnProperty(a)&&d.e(e[a],"Function"))e[a](b)}},_trackPageview:function(b){if(1<b.length&&b[1].charAt&&"/"==b[1].charAt(0)){e.c|=4;h.b.a.et=0;h.b.a.ep="";h.b.D?(h.b.a.nv=0,h.b.a.st=4):h.b.D=p;var a=h.b.a.u,d=h.b.a.su;h.b.a.u=n.protocol+"//"+document.location.host+b[1];
e.M||(h.b.a.su=document.location.href);h.b.j();h.b.a.u=a;h.b.a.su=d}},_trackEvent:function(b){2<b.length&&(e.c|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=f(b[1])+"*"+f(b[2])+(b[3]?"*"+f(b[3]):"")+(b[4]?"*"+f(b[4]):""),h.b.j())},_setCustomVar:function(b){if(!(4>b.length)){var a=b[1],d=b[4]||3;if(0<a&&6>a&&0<d&&4>d){e.s++;for(var s=(h.b.a.cv||"*").split("!"),r=s.length;r<a-1;r++)s.push("*");s[a-1]=d+"*"+f(b[2])+"*"+f(b[3]);h.b.a.cv=s.join("!");b=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,
"");""!==b?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(b),c.age):h.b.ka("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"==a[1].charAt(0)?n.protocol+"//"+window.location.host+a[1]:a[1],e.M=p)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),e.c|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=l.stringify(b),h.b.j())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.c|=32,h.b.a.et=93,h.b.a.ep=a,h.b.j()},_trackRTPageview:function(b){b=
b[1];d.e(b,"Object")&&(a(b),b=l.stringify(b),512>=encodeURIComponent(b).length&&(e.c|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.e(b,"Object")){a(b);b=encodeURIComponent(l.stringify(b));var f=function(a){var b=h.b.a.rt;e.c|=128;h.b.a.et=90;h.b.a.rt=a;h.b.j();h.b.a.rt=b},g=b.length;if(900>=g)f.call(this,b);else for(var g=Math.ceil(g/900),s="block|"+Math.round(Math.random()*n.r).toString(16)+"|"+g+"|",r=[],k=0;k<g;k++)r.push(k),r.push(b.substring(900*k,900*k+900)),f.call(this,s+r.join("|")),
r=[]}},_setUserId:function(a){a=a[1];if(d.e(a,"String")||d.e(a,"Number")){var f=h.b.C(),k="hm-"+h.b.a.v;e.O=e.O||Math.round(Math.random()*n.r);g.log("//datax.baidu.com/x.gif?si="+c.id+"&dm="+encodeURIComponent(f)+"&ac="+encodeURIComponent(a)+"&v="+k+"&li="+e.O+"&rnd="+Math.round(Math.random()*n.r))}}};e.init();h.T=e;return h.T})();
(function(){function a(){"undefined"==typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=p,this.a={},this.D=t,this.init())}var f=mt.url,g=mt.I,d=mt.t,l=mt.lang,n=mt.cookie,k=mt.h,e=mt.localStorage,b=mt.sessionStorage,m=h.z,u=h.p;a.prototype={F:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length==a.length},N:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},q:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.N(a,c.dm[b]))return p}else{var d=f.K(a);if(d&&this.F(d,c.dm[b]))return p}return t},C:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.F(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},J:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.N(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},ba:function(){if(!document.referrer)return m.g-m.l>c.vdur?1:4;var a=
t;this.q(document.referrer)&&this.q(document.location.href)?a=p:(a=f.K(document.referrer),a=this.F(a||"",document.location.hostname));return a?m.g-m.l>c.vdur?1:4:3},getData:function(a){try{return n.get(a)||b.get(a)||e.get(a)}catch(d){}},setData:function(a,d,f){try{n.set(a,d,{domain:this.C(),path:this.J(),B:f}),f?e.set(a,d,f):b.set(a,d)}catch(g){}},ka:function(a){try{n.set(a,"",{domain:this.C(),path:this.J(),B:-1}),b.remove(a),e.remove(a)}catch(d){}},pa:function(){var a,b,d,e,f;m.l=this.getData("Hm_lpvt_"+
c.id)||0;13==m.l.length&&(m.l=Math.round(m.l/1E3));b=this.ba();a=4!=b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13==e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<m.g-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(m.g);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=m.g,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,m.g);d=m.g==this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.q(document.location.href)&&
(""===document.referrer||this.q(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},oa:function(){for(var a=[],b=0,d=m.Q.length;b<d;b++){var e=m.Q[b],f=this.a[e];"undefined"!=typeof f&&""!==f&&a.push(e+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},qa:function(){this.pa();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=k.la;this.a.cl=k.colorDepth+"-bit";
this.a.ln=k.language;this.a.ja=k.javaEnabled?1:0;this.a.ck=k.cookieEnabled?1:0;this.a.lo="number"==typeof _bdhm_top?1:0;this.a.fl=d.ca();this.a.v="1.0.77";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1==this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=f.k(a,m.fa)||"";this.a.cp=f.k(a,m.ga)||"";this.a.cw=f.k(a,m.ea)||"";this.a.ci=f.k(a,m.da)||"";this.a.cf=f.k(a,m.ha)||""},init:function(){try{this.qa(),0===this.a.nv?this.na():this.H(".*"),h.b=this,this.U(),
u.o("pv-b"),this.ma()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(m.protocol+"//"+m.P+"?"+b.join("&"))}},ma:function(){function a(){u.o("pv-d")}"undefined"===typeof window._bdhm_autoPageview||window._bdhm_autoPageview===p?(this.D=p,this.a.et=0,this.a.ep="",this.j(a)):a()},j:function(a){var b=this;b.a.rnd=Math.round(Math.random()*m.r);u.o("stag-b");var d=m.protocol+"//"+
m.P+"?"+b.oa();u.o("stag-d");b.R(d);g.log(d,function(d){b.H(d);l.e(a,"Function")&&a.call(b)})},U:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),d=-1<document.referrer.indexOf(m.S)?p:t,e=f.k(a,"jn"),g=/^heatlink$|^select$/.test(e);a&&(b.test(a)&&d&&g)&&(a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",m.protocol+"//"+c.js+e+".js?"+this.a.rnd),e=document.getElementsByTagName("script")[0],e.parentNode.insertBefore(a,
e))},R:function(a){var d=b.get("Hm_unsent_"+c.id)||"",e=this.a.u?"":"&u="+encodeURIComponent(document.location.href),d=encodeURIComponent(a.replace(/^https?:\/\//,"")+e)+(d?","+d:"");b.set("Hm_unsent_"+c.id,d)},H:function(a){var d=b.get("Hm_unsent_"+c.id)||"";d&&((d=d.replace(RegExp(encodeURIComponent(a.replace(/^https?:\/\//,"")).replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),"").replace(/,$/,""))?b.set("Hm_unsent_"+c.id,d):b.remove("Hm_unsent_"+c.id))},na:function(){var a=this,d=b.get("Hm_unsent_"+
c.id);if(d)for(var d=d.split(","),e=function(b){g.log(m.protocol+"//"+decodeURIComponent(b).replace(/^https?:\/\//,""),function(b){a.H(b)})},f=0,k=d.length;f<k;f++)e(d[f])}};return new a})();
(function(){if("378f3aa9b8779062c8de4dc247dd8874"===c.id){var a={click:function(){for(var a=[],d=[].slice.call(document.getElementsByTagName("a")),d=[].concat.apply(d,document.getElementsByTagName("area")),b=/openZoosUrl\(/,f=0,g=d.length;f<g;f++)b.test(d[f].getAttribute("onclick"))&&a.push(d[f]);return a}},f=function(a,d){for(var b in a)if(a.hasOwnProperty(b)&&d.call(a,b,a[b])===t)return t},g=function(a,d){return Object.prototype.toString.call(a)==="[object "+d+"]"};window._hmt=window._hmt||[];var d,
l="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),n=function(a,e){if(d===e){window._hmt.push(["_trackPageview",l+a]);for(var b=+new Date;500>=+new Date-b;);return t}if(g(e,"Array")||g(e,"NodeList"))for(var b=0,f=e.length;b<f;b++)if(d===e[b]){window._hmt.push(["_trackPageview",l+a+"/"+(b+1)]);for(b=+new Date;500>=+new Date-b;);return t}};(function(a,d,b){a.addEventListener?a.addEventListener(d,b,p):a.attachEvent&&a.attachEvent("on"+d,b)})(document,"click",function(k){k=k||window.event;d=k.target||k.srcElement;
var e={};for(f(a,function(a,d){e[a]=g(d,"Function")?d():document.getElementById(d)});d&&d!==document&&f(e,n)!==t;)d=d.parentNode})}})();})();
